MVP documentation
passcryptum/docs pull request #2
Opened 2023-11-18 15:26 UTC by raccoonsw

2023-11-18 16:32 UTC, nelkor reviewed
Отличный старт! У нас будет неплохая шпаргалка по применению Passcryptum. Далее можно будет расширять "знания" рекомендациями и описанием принципов работы.

Чего не хватает уже сейчас: было бы неплохо написать что-нибудь про установку PWA. На текущий момент я считаю установленное PWA предпочтительным способом работы с Passcryptum. А вот скачивание HTML-файла — это что-то для хакеров уже (менее удобно, выше риск возникновения проблем, но ещё более закрыто).

В этом репозитории установлен Prettier. Более того, GitHub гоняет Prettier, чтобы проверить правильность форматирования кода. Сейчас у этого PR красный крестик, то есть проверка не прошла. Чтобы запустить автоматический фикс, следует ввести "npm run format:fix".

Ещё у вкладки браузера нет иконки. Надо разобраться, как добавить её в VitePress, но не обязательно в рамках этой задачи.

2023-11-18 16:32 UTC, nelkor commented on pages/overview/get-started.md
> +1. [Find the service](../how-tos/services.md#find-service) from the search bar.
Я так полагаю, "Get started" описывает алгоритм действий с нуля. После создания первого сервиса его не придётся искать в строке поиска, он будет сразу же на экране.

2023-11-18 16:32 UTC, nelkor commented on pages/how-tos/pin.md
> +If you forgot a PIN, delete it and set a new one.
В целом, норм формулировка, но шаг "удаления забытого PIN" бросается в глаза и выглядит лишним. Я бы сказал, просто зайбейте на PIN, войдите в аккаунт по исходному паролю и установите новый PIN (старый не обязательно именно удалять, он просто заменится новым).

2023-11-18 16:32 UTC, nelkor commented on pages/.vitepress/config.mts
> +      // },
Не надо оставлять закоментированный код.

2023-11-18 16:32 UTC, nelkor commented on pages/how-tos/general.md
> +1. [Export services](storage.md#export-services) from the web application. The file will be downloaded.
Это действительно работает (единички превращаются в правильные числа). При этом редакторы кода ругаются и предлагают исправить на 1, 2, 3...

И в "подсказках" по Markdown в интернете тоже предлагают писать сразу нужные номера. Интересно, почему так?

2023-11-18 18:08 UTC, raccoonsw commented on pages/how-tos/general.md
> +1. [Export services](storage.md#export-services) from the web application. The file will be downloaded.
я думаю пошло это из диалекта маркдауна. просто это более удобный способ для списков, т.к. можно не заметить неправильную нумерацию. предлагаешь писать, как хочет линтер?

2023-11-18 18:08 UTC, raccoonsw commented on pages/.vitepress/config.mts
> +      // },
надо, если я к этому вернусь

2023-11-18 18:31 UTC, nelkor commented on pages/.vitepress/config.mts
> +      // },
Это такое правило: закоментированный код не может попасть в основную ветку. Этот Pull Request как раз идёт в основную ветку.

2023-11-18 18:32 UTC, nelkor commented on pages/how-tos/general.md
> +1. [Export services](storage.md#export-services) from the web application. The file will be downloaded.
Если это какой-то неофициальный дилект, то лучше исправить. Потому что потом окажется, что чем-то это поддерживается, а чем-то другим — нет.

2023-11-19 06:36 UTC, raccoonsw commented on pages/.vitepress/config.mts
> +      // },
а как я вспомню об этом?

2023-11-19 06:37 UTC, raccoonsw commented on pages/how-tos/general.md
> +1. [Export services](storage.md#export-services) from the web application. The file will be downloaded.
я думаю официальный. я бы не стала править. очень сложно поддерживать

2023-11-19 06:38 UTC, raccoonsw commented on pages/how-tos/pin.md
> +If you forgot a PIN, delete it and set a new one.
принято. поправила

2023-11-19 06:47 UTC, raccoonsw commented on pages/overview/get-started.md
> +1. [Find the service](../how-tos/services.md#find-service) from the search bar.
принято. поправила

2023-11-19 06:47 UTC, raccoonsw commented on pages/.vitepress/config.mts
> +      // },
договорились в чате

2023-11-27 06:24 UTC, nelkor requested changes
Осталось поправить пару ссылок и внести правки от переводчика.

2023-11-27 06:24 UTC, nelkor commented on pages/.vitepress/config.mts
> +      { text: 'GitHub', link: '/markdown-examples' },
Вот так ссылка будет работать правильно.

```suggestion
      { text: 'GitHub', link: 'https://github.com/nelkor/passcryptum' },
```

2023-11-27 06:24 UTC, nelkor commented on pages/.vitepress/config.mts
> +        link: 'https://github.com/nelkor/passcryptum',
Здесь должна быть ссылка на канал в Телеграме.

```suggestion
        link: 'https://t.me/passcryptum',
```

2023-11-27 17:06 UTC, nelkor approved these changes

2023-11-27 17:07 UTC, merged